import { StyleSheet, Platform } from "react-native";
import { CORES } from "./cores";

const estilos = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.bg },
  avisosContainer: {
    position: "absolute",
    top: Platform.OS === "ios" ? 58 : 34,
    left: 14,
    right: 14,
    zIndex: 9999,
  },
  avisoCard: {
    backgroundColor: CORES.info,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 7,
  },
  avisoErro: { backgroundColor: CORES.perigo },
  avisoSucesso: { backgroundColor: CORES.sucesso },
  avisoAlerta: { backgroundColor: CORES.alerta },
  avisoTitulo: { color: CORES.branco, fontWeight: "800", fontSize: 14 },
  avisoMensagem: { color: CORES.branco, marginTop: 3, fontSize: 12.5, lineHeight: 17 },

  // ---- Auth (login/cadastro) ----
  telaAuthScroll: { flexGrow: 1, backgroundColor: CORES.bg },
  heroAuth: {
    backgroundColor: CORES.campoEscuro,
    paddingTop: 74,
    paddingBottom: 46,
    alignItems: "center",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  heroDecoracaoA: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: CORES.campoEscuro2,
    opacity: 0.55,
    top: -70,
    right: -50,
  },
  heroDecoracaoB: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: CORES.dourado,
    opacity: 0.12,
    bottom: -50,
    left: -40,
  },
  heroBolaWrap: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: CORES.dourado,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  heroBola: { fontSize: 32 },
  heroTitulo: {
    fontSize: 28,
    fontWeight: "800",
    color: CORES.branco,
    letterSpacing: 0.3,
  },
  heroSubtitulo: {
    fontSize: 13.5,
    color: "#CFE8DA",
    marginTop: 6,
    textAlign: "center",
    paddingHorizontal: 40,
  },

  cardAuth: {
    backgroundColor: CORES.branco,
    marginHorizontal: 22,
    marginTop: -26,
    borderRadius: 18,
    padding: 22,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
  },
  tituloCard: {
    fontSize: 17,
    fontWeight: "700",
    color: CORES.texto,
    marginBottom: 16,
  },

  rotuloCampo: {
    fontSize: 12.5,
    fontWeight: "600",
    color: CORES.textoSuave,
    marginBottom: 6,
  },
  campoWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.inputBg,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: 10,
    height: 46,
    paddingHorizontal: 12,
  },
  campoIcone: { fontSize: 15, marginRight: 8 },
  campoInput: { flex: 1, height: "100%", color: CORES.texto, fontSize: 15 },

  botao: {
    width: "100%",
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  botaoTexto: { fontSize: 15, fontWeight: "700" },

  linkTexto: { textAlign: "center", color: CORES.textoSuave, fontSize: 13.5 },
  linkTextoForte: { color: CORES.campoEscuro, fontWeight: "700" },

  // ---- Topo (header interno) ----
  topo: {
    backgroundColor: CORES.campoEscuro,
    paddingTop: Platform.OS === "ios" ? 56 : 40,
    paddingBottom: 18,
    paddingHorizontal: 10,
    overflow: "hidden",
  },
  topoDecoracaoA: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: CORES.campoEscuro2,
    opacity: 0.5,
    top: -60,
    right: -30,
  },
  topoDecoracaoB: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: CORES.dourado,
    opacity: 0.1,
    bottom: -40,
    left: -20,
  },
  topoLinha: { flexDirection: "row", alignItems: "center" },
  topoBotaoIcone: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  topoBotaoIconeTexto: { color: CORES.branco, fontSize: 22, fontWeight: "700" },
  topoTitulo: { color: CORES.branco, fontSize: 18, fontWeight: "800" },
  topoSubtitulo: { color: "#CFE8DA", fontSize: 12.5, marginTop: 2 },
  topoBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: CORES.perigo,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  topoBadgeTexto: { color: CORES.branco, fontSize: 9.5, fontWeight: "700" },

  // ---- Conteúdo geral ----
  conteudoScroll: { padding: 16, paddingBottom: 40 },

  cardResumo: {
    backgroundColor: CORES.branco,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginTop: -30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  resumoNome: { fontSize: 15.5, fontWeight: "700", color: CORES.texto },
  resumoEmail: { fontSize: 12.5, color: CORES.textoSuave, marginTop: 2 },
  resumoPontosBox: { alignItems: "center", paddingLeft: 10 },
  resumoPontosNumero: {
    fontSize: 20,
    fontWeight: "800",
    color: CORES.campoEscuro,
  },
  resumoPontosLabel: {
    fontSize: 10.5,
    color: CORES.textoSuave,
    fontWeight: "600",
  },

  linhaBotoesAcao: { flexDirection: "row", marginTop: 18 },

  cardFormInline: {
    backgroundColor: CORES.branco,
    borderRadius: 14,
    padding: 16,
    marginTop: 14,
    borderWidth: 1,
    borderColor: CORES.borda,
  },

  secaoTitulo: {
    fontSize: 15,
    fontWeight: "700",
    color: CORES.texto,
    marginTop: 22,
    marginBottom: 10,
  },
  secaoTituloSemMargem: {
    fontSize: 15,
    fontWeight: "700",
    color: CORES.texto,
    marginBottom: 8,
  },
  participantesLista: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
  },
  participanteChip: {
    backgroundColor: CORES.inputBg,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  participanteChipTexto: {
    color: CORES.textoSuave,
    fontSize: 12,
    fontWeight: "600",
  },

  cardBolao: {
    backgroundColor: CORES.branco,
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  cardBolaoFaixa: {
    width: 4,
    height: "100%",
    backgroundColor: CORES.dourado,
    borderRadius: 2,
    position: "absolute",
    left: 0,
  },
  cardBolaoNome: {
    fontSize: 15,
    fontWeight: "700",
    color: CORES.texto,
    marginRight: 8,
  },
  cardBolaoInfo: { fontSize: 12.5, color: CORES.textoSuave, marginTop: 4 },
  cardBolaoSeta: { fontSize: 24, color: "#CBD5E1", fontWeight: "700" },

  selo: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20 },
  seloTexto: { fontSize: 10.5, fontWeight: "700", textTransform: "uppercase" },

  avatar: { alignItems: "center", justifyContent: "center" },
  avatarTexto: { fontWeight: "800" },

  vazioContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  vazioTexto: {
    color: CORES.textoSuave,
    fontSize: 13.5,
    textAlign: "center",
    paddingHorizontal: 30,
  },

  // ---- Abas do bolão ----
  abas: {
    flexDirection: "row",
    backgroundColor: CORES.branco,
    marginTop: -18,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  abaBotao: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 9,
    alignItems: "center",
  },
  abaBotaoAtiva: { backgroundColor: CORES.campoEscuro },
  abaTexto: { fontSize: 13.5, fontWeight: "600", color: CORES.textoSuave },
  abaTextoAtivo: { color: CORES.branco },

  // ---- Partidas ----
  cardPartida: {
    backgroundColor: CORES.branco,
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  cardPartidaTopo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  cardPartidaData: { fontSize: 12, color: CORES.textoSuave, fontWeight: "600" },
  timesLinha: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  timeNome: {
    flex: 1,
    fontSize: 14.5,
    fontWeight: "700",
    color: CORES.texto,
    textAlign: "center",
  },
  vsTexto: {
    fontSize: 12,
    color: CORES.textoSuave,
    fontWeight: "700",
    marginHorizontal: 10,
  },
  placarFinal: {
    fontSize: 17,
    fontWeight: "800",
    color: CORES.campoEscuro,
    marginHorizontal: 10,
  },

  palpiteBloco: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    paddingTop: 12,
  },
  placarContainer: { flexDirection: "row", alignItems: "center" },
  inputPlacar: {
    width: 44,
    height: 40,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: 8,
    textAlign: "center",
    backgroundColor: CORES.inputBg,
    fontSize: 15,
    fontWeight: "700",
    color: CORES.texto,
  },
  txtX: {
    fontSize: 13,
    fontWeight: "700",
    marginHorizontal: 10,
    color: CORES.textoSuave,
  },

  faixaPontos: {
    marginTop: 10,
    backgroundColor: CORES.sucessoBg,
    borderRadius: 8,
    padding: 10,
  },
  faixaPontosTexto: { fontSize: 12.5, color: CORES.sucesso, fontWeight: "600" },

  organizadorBloco: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    paddingTop: 10,
  },
  linkOrganizador: { fontSize: 12.5, color: CORES.alerta, fontWeight: "700" },

  // ---- Ranking ----
  cardRanking: {
    backgroundColor: CORES.branco,
    borderRadius: 14,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  linhaRanking: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  posicaoRanking: {
    width: 26,
    fontSize: 15,
    fontWeight: "800",
    color: CORES.textoSuave,
    textAlign: "center",
  },
  nomeRanking: { fontSize: 14, fontWeight: "700", color: CORES.texto },
  detalheRanking: { fontSize: 11.5, color: CORES.textoSuave, marginTop: 2 },
  pontosRanking: { fontSize: 15, fontWeight: "800", color: CORES.campoEscuro },

  // ---- Notificações ----
  cardNotificacao: {
    flexDirection: "row",
    backgroundColor: CORES.branco,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  cardNotificacaoNaoLida: {
    borderColor: CORES.dourado,
    backgroundColor: "#FFFDF5",
  },
  pontoNaoLido: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CORES.dourado,
    marginRight: 10,
    marginTop: 5,
  },
  notificacaoTitulo: { fontSize: 14, fontWeight: "700", color: CORES.texto },
  notificacaoMensagem: {
    fontSize: 12.5,
    color: CORES.textoSuave,
    marginTop: 3,
  },
});

export default estilos;
